// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFPab6x3D6MH235fRS3w7t2giGDN1UZ7g',
    appId: '1:606090569773:web:bc4bc8009fda5e4b78f0a4',
    messagingSenderId: '606090569773',
    projectId: 'bootcamp4-92330',
    authDomain: 'bootcamp4-92330.firebaseapp.com',
    storageBucket: 'bootcamp4-92330.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjDjwF7KMB58_2E-Ko456VuZyp6THvSCY',
    appId: '1:606090569773:android:2bf537556777058d78f0a4',
    messagingSenderId: '606090569773',
    projectId: 'bootcamp4-92330',
    storageBucket: 'bootcamp4-92330.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbdxoAS-tU88go5iMvI05wC_YnpQpWLFQ',
    appId: '1:606090569773:ios:586e9ce18729d1a178f0a4',
    messagingSenderId: '606090569773',
    projectId: 'bootcamp4-92330',
    storageBucket: 'bootcamp4-92330.appspot.com',
    iosBundleId: 'com.example.bootcampGrup4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbdxoAS-tU88go5iMvI05wC_YnpQpWLFQ',
    appId: '1:606090569773:ios:586e9ce18729d1a178f0a4',
    messagingSenderId: '606090569773',
    projectId: 'bootcamp4-92330',
    storageBucket: 'bootcamp4-92330.appspot.com',
    iosBundleId: 'com.example.bootcampGrup4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFPab6x3D6MH235fRS3w7t2giGDN1UZ7g',
    appId: '1:606090569773:web:d5dcefe51ded507078f0a4',
    messagingSenderId: '606090569773',
    projectId: 'bootcamp4-92330',
    authDomain: 'bootcamp4-92330.firebaseapp.com',
    storageBucket: 'bootcamp4-92330.appspot.com',
  );
}
